vo=gpu-next
gpu-api=vulkan
macos-render-timer=feedback

hwdec=no
vd-lavc-dr=auto

icc-profile-auto=yes

target-colorspace-hint=no
target-colorspace-hint-mode=target

hdr-contrast-recovery=0.30
hdr-peak-percentile=99.995

deband=no
dither-depth=no

video-sync=audio
interpolation=no

cscale=ewa_lanczossharp
scale=ewa_lanczossharp 
dscale=hermite

cscale-antiring=0
scale-antiring=0

correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes

cursor-autohide=200
cursor-autohide-fs-only=yes
fullscreen=yes
hidpi-window-scale=no
hr-seek=no
idle=once
input-builtin-bindings=no
input-default-bindings=no
keep-open=yes
loop-playlist=inf
macos-fs-animation-duration=0
native-fs=yes
native-keyrepeat=yes

audio-file-auto=exact
volume=100
volume-max=100

blend-subtitles=no
embeddedfonts=yes
secondary-sid=no
sub-auto=fuzzy
sub-fix-timing=no
sub-shaper=complex

ytdl-format=bv*+ba/b

glsl-shaders='~~/shaders/hdeband.glsl:~~/shaders/CfL_Prediction.glsl:~~/shaders/ArtCNN_C4F16.glsl'

[HDR]
profile-desc=HDR
profile-cond=(p["video-params/gamma"] == "pq") or (p["video-params/gamma"] == "hlg")
profile-restore=copy
icc-profile-auto=no
target-colorspace-hint=yes
