vo=gpu-next
gpu-api=vulkan
macos-render-timer=feedback

hwdec=videotoolbox
vd-lavc-dr=auto

icc-profile-auto=yes

target-colorspace-hint=no
target-colorspace-hint-mode=target

hdr-contrast-recovery=0.30
hdr-peak-percentile=99.995

deband=no
dither-depth=no

video-sync=audio
interpolation=no

cscale=ewa_lanczossharp
scale=ewa_lanczossharp 
dscale=hermite

cscale-antiring=0
scale-antiring=0

correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes

cursor-autohide=200
cursor-autohide-fs-only=yes
fullscreen=yes
hidpi-window-scale=no
idle=once
input-builtin-bindings=no
input-default-bindings=no
keep-open=yes
loop-playlist=inf
macos-fs-animation-duration=0
native-fs=yes
native-keyrepeat=yes
osd-font='SFPro-Semibold'

audio-file-auto=exact
audio-file-paths=audio:dub:sound:**
alang=ja,jp,jpn,jap,Japanese,en,eng,English,uk
volume=100
volume-max=100

sub-auto=fuzzy
sub-file-paths=sub:subs:subtitles:**
slang=uk,en,eng,English

blend-subtitles=no
embeddedfonts=yes
secondary-sid=no
sub-ass-override=force
sub-ass-style-overrides=Kerning=yes
sub-border-color='#000000'
sub-border-size=3
sub-color='#FFFFFF'
sub-fix-timing=no
sub-font='SFPro-Semibold'
sub-font-size=48
sub-shaper=complex
sub-use-margins=no

ytdl-format=bv*+ba/b

glsl-shaders='~~/shaders/hdeband.glsl:~~/shaders/CfL_Prediction.glsl:~~/shaders/ArtCNN_C4F16.glsl'

[HDR]
profile-desc=HDR
profile-cond=(p["video-params/gamma"] == "pq") or (p["video-params/gamma"] == "hlg")
profile-restore=copy
icc-profile-auto=no
target-colorspace-hint=yes
