vo=gpu-next
gpu-api=vulkan
gpu-context=macvk
macos-force-dedicated-gpu=yes
macos-render-timer=feedback

hwdec=auto-copy

vd-lavc-dr=no 
vulkan-async-transfer=yes
vulkan-async-compute=yes
vulkan-swap-mode=fifo

allow-delayed-peak-detect=no
icc-profile-auto=yes
icc-intent=0
gamut-mapping-mode=perceptual
sdr-adjust-gamma=yes
target-contrast=1000000
target-prim=display-p3
target-trc=srgb
treat-srgb-as-power22=no

icc-use-luma=no
hdr-compute-peak=no
hdr-contrast-recovery=0.30
hdr-peak-percentile=99.995 
hdr-reference-white=600
target-colorspace-hint=no
target-colorspace-hint-mode=target
target-peak=600
tone-mapping=spline

deband=no
dither-depth=no

video-sync=audio
interpolation=no

vd-lavc-threads=0
vd-queue-enable=yes
ad-lavc-threads=2
ad-queue-enable=yes

cscale=ewa_lanczossharp
scale=ewa_lanczossharp 
dscale=hermite

scale-antiring=0.6

correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes

force-window=yes
fullscreen=yes
hidpi-window-scale=no
idle=once
macos-fs-animation-duration=0
native-fs=yes
native-keyrepeat=yes
terminal=no

osc=no
osd-font='SFPro-Semibold'
osd-on-seek=no

alang=ja,jp,jpn,jap,Japanese,en,eng,English,uk
ao=coreaudio
ad-lavc-downmix=no
audio-channels=stereo
audio-file-auto=no
audio-format=floatp
audio-normalize-downmix=yes
audio-resample-cutoff=0.91
audio-resample-linear=yes
audio-samplerate=48000
audio-swresample-o-append=resampler=soxr
audio-swresample-o-append=precision=33
audio-swresample-o-append=osf=fltp
audio-swresample-o-append=osr=48000
audio-swresample-o-append=cheby=1
audio-swresample-o-append=dither_method=shibata
audio-swresample-o-append=cutoff=0.91
gapless-audio=no
replaygain=track
volume=100
volume-max=100

sub-auto=fuzzy
sub-file-paths=sub:subs:subtitles:**
slang=uk,ru,rus,en,eng,English

sub-font='SFPro-Semibold'
sub-font-size=48
sub-border-size=3
sub-color='#FFFFFF'
sub-border-color='#000000'

blend-subtitles=no
embeddedfonts=yes
secondary-sid=no
sub-ass-override=force
sub-ass-style-overrides=Kerning=yes,FontName=SFPro-Semibold,Bold=0
sub-fix-timing=no 
sub-shaper=simple
sub-use-margins=no

ytdl-format=bv*+ba/b

cache=yes
cursor-autohide=200
cursor-autohide-fs-only=yes
input-default-bindings=no
input-builtin-bindings=no
keep-open=always
loop-playlist=inf
msg-level=all=warn
reset-on-next-file=all
resume-playback=no
save-position-on-quit=no
use-filedir-conf=no
watch-later-options-remove=all

glsl-shaders='~~/shaders/hdeband.glsl:~~/shaders/CfL_Prediction.glsl:~~/shaders/ArtCNN_C4F16.glsl'

[HDR]
profile-cond=(p["video-params/primaries"] == "bt.2020") and (p["video-params/gamma"] == "pq")
profile-restore=copy
icc-profile-auto=no
target-colorspace-hint=yes
target-peak=1000
target-prim=bt.2020
target-trc=pq
